platform :ios, '7.0'
pod 'XMPPFramework/Core', :podspec => 'xmpp.podspec'
pod 'XMPPFramework/Reconnect', :podspec => 'xmpp.podspec'
pod 'XMPPFramework/XEP-0045', :podspec => 'xmpp.podspec'
pod 'XMPPFramework/Roster', :podspec => 'xmpp.podspec'

pod 'MobilisMXi', :path => '/Users/cmdaltent/Development/Projects/Mobilis/Mobilis'
#Development
#pod 'MobilisMXi', :git => 'https://github.com/mobilis/mobilis.git'
